In [62]:
import pandas as pd
import csv
import os

In [65]:
data_dict = pd.read_csv('/Users/ianbury/Springboard/collegeScorecard/CollegeScorecardDataDictionary.csv')
data = {}
directory = os.fsencode('/Users/ianbury/Springboard/collegeScorecard/CollegeScorecard_Raw_Data/')

for file in os.listdir(directory):
    filename = os.fsdecode(file)
    if filename.endswith('.csv'):
        
        data[filename[7:12]] = pd.read_csv('/Users/ianbury/Springboard/collegeScorecard/CollegeScorecard_Raw_Data/'+filename)

/Users/ianbury/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/ianbury/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (1,6,442,451,598,607,611,620,624,633,789,802,806,815,893,906,971,984,997,1153,1166,1407,1408,1411,1424,1425,1426,1431,1432,1433,1437,1438,1439,1440,1445,1446,1447,1451,1452,1453,1454,1459,1460,1461,1465,1466,1467,1468,1473,1474,1475,1479,1480,1481,1482,1487,1488,1489,1501,1502,1537,1538,1539,1540,1541,1542,1606,1609,1610,1611,1613,1614,1615,1616,1688,1689,1690,1691,1692) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/ianbury/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (1,6,1408,1431,1432,1433,1475,1489,1537,1538,1539,1540,1542,1606,1610,1611,1614,1615,1616,1729) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/ianbury/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (1,1447,1537,1540,1542,1606,1614,1615) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/ianbury/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (1,1537,1540,1542,1606,1614,1615) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/ianbury/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (1,6,1461,1561,1729) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/ianbury/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (1537,1540,1542,1575,1606,1614,1615,1729) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/ianbury/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (1537,1540,1542,1547,1548,1549,1561,1575,1606,1614,1615,1729) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/ianbury/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (6,1169,1170,1171,1172,1173,1174,1175,1177,1178,1179,1183,1184,1185,1186,1187,1188,1196,1199,1200,1201,1209,1212,1213,1214,1222,1223,1224,1225,1226,1227,1235,1236,1237,1238,1239,1240,1248,1250,1251,1252,1253,1255,1257,1261,1263,1264,1265,1266,1268,1270,1274,1275,1276,1277,1278,1279,1283,1287,1288,1289,1290,1291,1292,1296,1303,1316,1326,1327,1328,1329,1330,1331,1335,1339,1340,1341,1342,1343,1344,1348,1379,1380,1381,1382,1383,1384,1385,1386,1387,1388,1389,1390,1391,1392,1393,1394,1395,1396,1397,1398,1399,1400,1401,1402,1403,1404,1405,1406,1407,1411,1426,1427,1475,1476,1479,1480,1483,1484,1487,1488,1489,1490,1491,1492,1493,1494,1495,1496,1497,1498,1499,1500,1501,1502,1503,1517,1529,1530,1532,1537,1540,1541,1542,1575,1576,1577,1578,1579,1580,1581,1582,1583,1584,1585,1586,1587,1588,1589,1590,1591,1592,1593,1594,1595,1596,1597,1598,1599,1600,1601,1602,1606,1609,1610,1613,1614,1615,1708,1729) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/ianbury/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (6,9,1725,1726,1727,1728,1729,1743,1815,1816,1817,1818,1823,1824) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [64]:
data_dict

,NAME OF DATA ELEMENT,dev-category,developer-friendly name,API data type,VARIABLE NAME,VALUE,LABEL,SOURCE,NOTES
0,Unit ID for institution,root,id,integer,UNITID,NaN,NaN,IPEDS,Shown/used on consumer website.
1,8-digit OPE ID for institution,root,ope8_id,integer,OPEID,NaN,NaN,IPEDS,Shown/used on consumer website.
2,6-digit OPE ID for institution,root,ope6_id,integer,OPEID6,NaN,NaN,IPEDS,Shown/used on consumer website.
3,Institution name,school,name,autocomplete,INSTNM,NaN,NaN,IPEDS,Shown/used on consumer website.
4,City,school,city,autocomplete,CITY,NaN,NaN,IPEDS,Shown/used on consumer website.
5,State postcode,school,state,string,STABBR,NaN,NaN,IPEDS,Shown/used on consumer website.
6,ZIP code,school,zip,string,ZIP,NaN,NaN,IPEDS,NaN
7,Accreditor for institution,school,accreditor,string,ACCREDAGENCY,NaN,NaN,FSA,NaN
8,URL for institution's homepage,school,school_url,string,INSTURL,NaN,NaN,IPEDS,Shown/used on consumer website.
9,URL for institution's net price calculator,school,price_calculator_url,string,NPCURL,NaN,NaN,IPEDS,Shown/used on consumer website.
10,Predominant degree awarded (recoded 0s and 4s),school,degrees_awarded.predominant_recoded,integer,SCH_DEG,NaN,NaN,IPEDS/NSLDS,"Missing values, 0s, and 4s from PREDDEG recode..."
11,Schools that are on Heightened Cash Monitoring...,school,under_investigation,integer,HCM2,NaN,NaN,FSA,Shown/used on consumer website; Flag (1=HCM2)
12,Flag for main campus,school,main_campus,integer,MAIN,0.0,Not main campus,IPEDS,NaN
13,NaN,school,NaN,NaN,NaN,1.0,Main campus,NaN,NaN
14,Number of branch campuses,school,branches,integer,NUMBRANCH,NaN,NaN,IPEDS,NaN
15,Predominant undergraduate degree awarded\r 0 N...,school,degrees_awarded.predominant,integer,PREDDEG,0.0,Not classified,IPEDS,Shown/used on consumer website.
16,NaN,school,NaN,NaN,NaN,1.0,Predominantly certificate-degree granting,NaN,NaN
17,NaN,school,NaN,NaN,NaN,2.0,Predominantly associate's-degree granting,NaN,NaN
18,NaN,school,NaN,NaN,NaN,3.0,Predominantly bachelor's-degree granting,NaN,NaN
19,NaN,school,NaN,NaN,NaN,4.0,Entirely graduate-degree granting,NaN,NaN
20,Highest degree awarded\r 0 Non-degree-granting...,school,degrees_awarded.highest,integer,HIGHDEG,0.0,Non-degree-granting,IPEDS,Shown/used on consumer website.
21,NaN,school,NaN,NaN,NaN,1.0,Certificate degree,NaN,NaN
22,NaN,school,NaN,NaN,NaN,2.0,Associate degree,NaN,NaN
23,NaN,school,NaN,NaN,NaN,3.0,Bachelor's degree,NaN,NaN
24,NaN,school,NaN,NaN,NaN,4.0,Graduate degree,NaN,NaN
25,Control of institution,school,ownership,integer,CONTROL,1.0,Public,IPEDS,Shown/used on consumer website.
26,NaN,school,NaN,NaN,NaN,2.0,Private nonprofit,NaN,NaN
27,NaN,school,NaN,NaN,NaN,3.0,Private for-profit,NaN,NaN
28,FIPS code for state,school,state_fips,integer,ST_FIPS,1.0,Alabama,IPEDS,NaN
29,NaN,school,NaN,NaN,NaN,2.0,Alaska,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2030,"Percentage of full-time, not first-time studen...",completion,outcome_percentage.full_time.not_first_time.8y...,float,OMENRAP8_FTNFT,NaN,NaN,IPEDS,NaN
2031,"Percentage of full-time, not first-time studen...",completion,outcome_percentage.full_time.not_first_time.8y...,float,OMENRUP8_FTNFT,NaN,NaN,IPEDS,NaN
2032,"Adjusted cohort count of part-time, not first-...",completion,outcome_cohort.part_time.not_first_time.6yr,integer,OMACHT6_PTNFT,NaN,NaN,IPEDS,NaN
2033,"Percentage of part-time, not first-time studen...",completion,outcome_percentage.part_time.not_first_time.6y...,float,OMAWDP6_PTNFT,NaN,NaN,IPEDS,NaN
2034,"Adjusted cohort count of part-time, not first-...",completion,outcome_cohort.part_time.not_first_time.8yr,integer,OMACHT8_PTNFT,NaN,NaN,IPEDS,NaN
2035,"Percentage of part-time, not first-time studen...",completion,outcome_percentage.part_time.not_first_time.8y...,float,OMAWDP8_PTNFT,NaN,NaN,IPEDS,NaN
2036,"Percentage of part-time, not first-time studen...",completion,outcome_percentage.part_time.not_first_time.8y...,float,OMENRYP8_PTNFT,NaN,NaN,IPEDS,NaN
2037,"Percentage of part-time, not first-time studen...",completion,outcome_percentage.part_time.not_first_time.8y...,float,OMENRAP8_PTNFT,NaN,NaN,IPEDS,NaN
2038,"Percentage of part-time, not first-time studen...",completion,outcome_percentage.part_time.not_first_time.8y...,float,OMENRUP8_PTNFT,NaN,NaN,IPEDS,NaN
2039,"First-time, full-time student retention rate a...",student,retention_rate.four_year.full_time_pooled,float,RET_FT4_POOLED,NaN,NaN,IPEDS,"The proportion of full-time, first-time, degre..."
2040,"First-time, full-time student retention rate a...",student,retention_rate.lt_four_year.full_time_pooled,float,RET_FTL4_POOLED,NaN,NaN,IPEDS,ibid
2041,"First-time, part-time student retention rate a...",student,retention_rate.four_year.part_time_pooled,float,RET_PT4_POOLED,NaN,NaN,IPEDS,"The proportion of part-time, first-time, degre..."
2042,"First-time, part-time student retention rate a...",student,retention_rate.lt_four_year.part_time_pooled,float,RET_PTL4_POOLED,NaN,NaN,IPEDS,ibid
2043,"Adjusted cohort count for the first-time, full...",student,retention_rate.cohort.four_year.full_time_pooled,float,RET_FT_DEN4_POOLED,NaN,NaN,IPEDS,"The number of full-time, first-time, degree/ce..."
2044,"Adjusted cohort count for the first-time, full...",student,retention_rate.cohort.lt_four_year.full_time_p...,float,RET_FT_DENL4_POOLED,NaN,NaN,IPEDS,ibid
2045,"Adjusted cohort count for the first-time, part...",student,retention_rate.cohort.four_year.part_time_pooled,float,RET_PT_DEN4_POOLED,NaN,NaN,IPEDS,"The number of part-time, first-time, degree/ce..."
2046,"Adjusted cohort count for the first-time, part...",student,retention_rate.cohort.lt_four_year.part_time_p...,float,RET_PT_DENL4_POOLED,NaN,NaN,IPEDS,ibid
2047,Years used for rolling averages of full-time r...,student,retention_rate.pooled_yrs_used.full_time,integer,POOLYRSRET_FT,NaN,NaN,IPEDS,NaN
2048,Years used for rolling averages of part-time r...,student,retention_rate.pooled_yrs_used.part_time,integer,POOLYRSRET_PT,NaN,NaN,IPEDS,NaN
2049,"First-time, full-time student retention rate a...",student,retention_rate_suppressed.four_year.full_time_...,float,RET_FT4_POOLED_SUPP,NaN,NaN,IPEDS,Shown/used on consumer website; The proport...
2050,"First-time, full-time student retention rate a...",student,retention_rate_suppressed.lt_four_year.full_ti...,float,RET_FTL4_POOLED_SUPP,NaN,NaN,IPEDS,Shown/used on consumer website; ibid
2051,"First-time, part-time student retention rate a...",student,retention_rate_suppressed.four_year.part_time_...,float,RET_PT4_POOLED_SUPP,NaN,NaN,IPEDS,Shown/used on consumer website; The proport...
2052,"First-time, part-time student retention rate a...",student,retention_rate_suppressed.lt_four_year.part_ti...,float,RET_PTL4_POOLED_SUPP,NaN,NaN,IPEDS,Shown/used on consumer website; ibid
2053,"Transfer rate for first-time, full-time studen...",completion,transfer_rate.4yr.full_time_pooled,float,TRANS_4_POOLED,NaN,NaN,IPEDS,"The proportion of full-time, first-time, degre..."
2054,"Transfer rate for first-time, full-time studen...",completion,transfer_rate.less_than_4yr.full_time_pooled,float,TRANS_L4_POOLED,NaN,NaN,IPEDS,ibid
2055,Adjusted cohort count for transfer rate at fou...,completion,transfer_rate.cohort_4yr.full_time_pooled,integer,DTRANS_4_POOLED,NaN,NaN,IPEDS,"The number of full-time, first-time, degree/ce..."
2056,Adjusted cohort count for transfer rate at les...,completion,transfer_rate.cohort_less_than_4yr.full_time_p...,integer,DTRANS_L4_POOLED,NaN,NaN,IPEDS,ibid
2057,"Transfer rate for first-time, full-time studen...",completion,transfer_rate_suppressed.4yr.full_time_pooled,float,TRANS_4_POOLED_SUPP,NaN,NaN,IPEDS,"The proportion of full-time, first-time, degre..."
2058,"Transfer rate for first-time, full-time studen...",completion,transfer_rate_suppressed.less_than_4yr.full_ti...,float,TRANS_L4_POOLED_SUPP,NaN,NaN,IPEDS,ibid
2059,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN